### PR TITLE
#167749947 Configure Docker

### PR DESCRIPTION
**Pull request by davidteejay**
### What does this PR do?
Setup Docker for the project

### Description of Task to be completed?
Create the docker file and set up docker

### How should this be manually tested?
To test:
- Make sure you have Docker installed on your machine and you're logged in
- Run `docker build -t <your username>/node-web-app .`
- Run `docker images`.  You should see your image here
- Run `docker run -p 49160:8080 -d <your username>/node-web-app` to run the container in detached mode
- Run `docker logs <container id>` to view the logs of the container
- If you need to go into the container, run `docker exec -it <container id> /bin/bash`. You can replace `/bin/bash` with your favorite shell

### What are the relevant pivotal tracker stories?
[#167749947](https://www.pivotaltracker.com/story/show/167749947)

### CODE REVIEW

**Review by ldonjibson — COMMENTED** [review]
Are you assuming the docker wont handle postgresql database also? I did not see the configuration hence the reason for my question.

**Review by ldonjibson — CHANGES_REQUESTED** [review]
why not use the below to make sure both the package.json AND package-lock.json are copied?
`COPY package*.json ./`

**Review by ldonjibson — CHANGES_REQUESTED** [review]
`Dockerfile
.dockerignore
.gitignore
.git`
you can also add the above to the .dockerignore file

**Review by ldonjibson — COMMENTED** [review]
Lastly while cant we just use the **alpine** version of instead of the heavy node itself.
what i mean is `FROM node:10-alpine` instead of `FROM node:10`

**Review by davidteejay — COMMENTED** [review]
I've made the corrections to the PR

**Review by ldonjibson — APPROVED** [review]

**Review by hustlaviola — COMMENTED** [review]
Awesome. The commit messages can be made into one as suggested by the TTL, you can start your task directly on PT, then follow the convention. The first line will contain a summary of the task description, you can outline the steps taken to complete the task in the body, while the footer will trigger the PT board that you are done with the task. Here is an example

```
git commit -m"chore(coveralls): integrate coveralls code coverage service

- install coveralls, mocha-lcov-reporter, and nyc
- add coverage command to scripts tag in package.json
- update README.md with coveralls badge to display test coverage

[Finishes #167749945]"
```

**Review by ibraheem-adeyemo — COMMENTED** [review]
LGTM

**Review by daviddamilola — CHANGES_REQUESTED** [review]
Great.....it should follow this format 
```
COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .``

**Review by davidteejay — COMMENTED** [review]
All corrections have been made

**Comment by daviddamilola** [comment]
LGTM

**Comment by daviddamilola** [comment]
LGTM

**Review by daviddamilola — APPROVED** [review]

**Review by ascii-dev — APPROVED** [review]
LGTM

**Pull request merged**
